"""add radio transcript/audio fields to telemetry_readings

Revision ID: 3e684cecafad
Revises: c52ffe9984dd
Create Date: 2026-09-12 14:04:29.330683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e684cecafad'
down_revision: Union[str, Sequence[str], None] = 'c52ffe9984dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_readings', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('telemetry_readings', sa.Column('audio_url', sa.String(), nullable=True))
    op.add_column('telemetry_readings', sa.Column('audio_duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry_readings', 'audio_duration_ms')
    op.drop_column('telemetry_readings', 'audio_url')
    op.drop_column('telemetry_readings', 'transcript')
    # ### end Alembic commands ###
