"""add quality/availability/provenance/external_event_id to telemetry_readings

Revision ID: c52ffe9984dd
Revises: 65b46ca3ffd4
Create Date: 2026-09-12 13:42:01.102629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c52ffe9984dd'
down_revision: Union[str, Sequence[str], None] = '65b46ca3ffd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_readings', sa.Column('quality', sa.String(), nullable=True))
    op.add_column('telemetry_readings', sa.Column('availability', sa.String(), nullable=True))
    op.add_column(
        'telemetry_readings',
        sa.Column(
            'provenance',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column('telemetry_readings', sa.Column('external_event_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_telemetry_readings_external_event_id'), 'telemetry_readings', ['external_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_readings_external_event_id'), table_name='telemetry_readings')
    op.drop_column('telemetry_readings', 'external_event_id')
    op.drop_column('telemetry_readings', 'provenance')
    op.drop_column('telemetry_readings', 'availability')
    op.drop_column('telemetry_readings', 'quality')
    # ### end Alembic commands ###
